#!/usr/bin/env python3
"""Generate synthetic versioning-heavy saturation programs.

The shipped corpus exercises `push`/`pop` only shallowly (35 pushes across
every program, each immediately popped), so the diff-store discipline and the
frame machinery barely engage and every configuration measures the same. That
makes the saturation side of the store-selection question unmeasurable, which
is the gap these programs close.

Three families, each modelling a real search over an e-graph:

  portfolio  Wide and shallow. From one saturated base, try N candidate
             equalities independently: push, commit, saturate, pop. This is
             rule-portfolio or phase-ordering search - "which of these
             candidates helps?" - and it stresses mark/restore THROUGHPUT
             against a large common base, because every restore undoes a full
             saturation round.

  dfs        Deep and backtracking. A binary decision tree of depth d,
             unrolled in DFS order: at each node push, commit to one of two
             rewrites, saturate a little, recurse, pop. This is guided
             synthesis or branch-and-bound over rewrite choices, and it
             stresses RESTORE VOLUME plus the branch cut (a pop followed by a
             push at the same depth is a sibling, which is exactly the
             abandoned-future path).

  deepchain  Deep and narrow. Push d times without popping, adding work at
             every level, then unwind. Nothing else in the suite holds many
             live snapshots at once, which is the regime where per-frame
             compression is supposed to pay for itself in memory.

Usage:  gen_search_bench.py OUTDIR
"""

import os
import sys

HEADER = """;; TYPES: machine
;; GENERATED by benches/gen_search_bench.py - do not edit by hand.
;; {desc}
(sort G)
(constructor Zero () G)
(let z (Zero))
(constructor s (G) G)
(constructor add (G G) G)
(constructor mul (G G) G)
(rewrite (add z a) a)
(rewrite (add (s a) b) (s (add a b)))
(rewrite (mul z a) z)
(rewrite (mul (s a) b) (add b (mul a b)))
(birewrite (add a b) (add b a))
(birewrite (add (add a b) c) (add a (add b c)))
"""


def num(n):
    """Peano numeral term."""
    t = "z"
    for _ in range(n):
        t = f"(s {t})"
    return t


def base_terms(k):
    """A shared base the search branches from: k let-bound sums."""
    out = []
    for i in range(k):
        out.append(f"(let b{i} (add {num(i % 5 + 1)} (mul {num(i % 3 + 1)} {num(2)})))")
    return out


def portfolio(n_candidates, base_k, run_steps):
    L = [HEADER.format(desc=f"portfolio: {n_candidates} candidates over a {base_k}-term base")]
    L += base_terms(base_k)
    L.append(f"(run {run_steps})")
    for i in range(n_candidates):
        a = f"b{i % base_k}"
        b = f"b{(i * 7 + 3) % base_k}"
        L.append("(push)")
        # Commit to a speculative equality, then let congruence propagate it.
        L.append(f"(union {a} {b})")
        L.append(f"(run {run_steps})")
        L.append(f"(check (= {a} {b}))")
        L.append("(pop)")
    return "\n".join(L) + "\n"


def dfs(depth, base_k, run_steps):
    L = [HEADER.format(desc=f"dfs: binary decision tree of depth {depth} ({2 ** depth} leaves)")]
    L += base_terms(base_k)
    L.append(f"(run {run_steps})")

    def emit(level, path):
        if level == depth:
            i = (path * 13) % base_k
            L.append(f"(check (= b{i} b{i}))")
            return
        for choice in (0, 1):
            a = f"b{(path * 5 + choice) % base_k}"
            b = f"b{(path * 11 + choice * 3 + 1) % base_k}"
            L.append("(push)")
            L.append(f"(union {a} {b})")
            L.append(f"(run {run_steps})")
            emit(level + 1, path * 2 + choice)
            L.append("(pop)")

    emit(0, 1)
    return "\n".join(L) + "\n"


def deepchain(depth, base_k, run_steps):
    L = [HEADER.format(desc=f"deepchain: {depth} nested live frames, then unwind")]
    L += base_terms(base_k)
    L.append(f"(run {run_steps})")
    for i in range(depth):
        L.append("(push)")
        L.append(f"(union b{i % base_k} b{(i * 3 + 1) % base_k})")
        L.append(f"(let c{i} (add b{i % base_k} {num(i % 4 + 1)}))")
        L.append(f"(run {run_steps})")
    for _ in range(depth):
        L.append("(pop)")
    return "\n".join(L) + "\n"


def main():
    outdir = sys.argv[1] if len(sys.argv) > 1 else "."
    os.makedirs(outdir, exist_ok=True)
    progs = {
        "search-portfolio-small.rules.egg": portfolio(64, 24, 3),
        "search-portfolio.rules.egg": portfolio(512, 48, 4),
        "search-dfs-small.rules.egg": dfs(6, 24, 2),
        "search-dfs.rules.egg": dfs(10, 32, 2),
        "search-deepchain-small.rules.egg": deepchain(64, 24, 2),
        "search-deepchain.rules.egg": deepchain(256, 32, 2),
    }
    for name, text in progs.items():
        path = os.path.join(outdir, name)
        with open(path, "w") as f:
            f.write(text)
        pushes = text.count("(push)")
        print(f"{name}: {len(text.splitlines())} lines, {pushes} pushes")


if __name__ == "__main__":
    main()
